name: Check for typos

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: typos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Run spellcheck
        uses: crate-ci/typos@v1.50.2
